### ISSUE TITLE
view de contactos diferente a las otras

### ISSUE THREAD

**Issue by mmgescuelaup** [TrejoCode/doowerif#2]
@AlejandroTrejoCode ¿por que la vista de contactos es diferente a las vistas de footer y header?
Por su estructura se parece mas a las que utilizas en los modelos de la carpeta _model_.

¿Los archivos que están en la raíz de _application_  (index.php, login.php, register.php, y los otros .php no deberían estar en la carpeta de vistas _views_ ?

**Comment by TrejoCode** [comment]
Esto no se que es amiko ja, ja, pero todo ya está en Views, lo que no esté allí no es del proyecto, o es de pruebas.

**Comment by mmgescuelaup** [comment]
![image](https://user-images.githubusercontent.com/18332876/51411654-ae6be000-1b36-11e9-8daa-85bae8504a90.png)
